### ISSUE TITLE
~/sushiswap# npx hardhat node failed to start

### ISSUE THREAD

**Issue by bitcointap** [sushiswap/sushiswap#55]
Compilation finished successfully
Creating Typechain artifacts in directory types for target ethers-v5
Successfully generated Typechain artifacts!
Error HH604: Error running JSON-RPC server: ERROR processing skip func of /root/sushiswap/deploy/SushiMaker.js:
Error: Cannot find module '@uniswap/v2-core/build/IUniswapV2Pair.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/sushiswap/node_modules/@sushiswap/sdk/dist/sdk.cjs.development.js:18:38)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

For more info go to https://hardhat.org/HH604 or run Hardhat with --show-stack-traces

**Comment by bitcointap** [comment]
Please help to solve my problem

**Comment by bitcointap** [comment]
yarn ropsten:deploy

The command has the same exception

**Comment by VitaliyInshakov** [comment]
Yes, this error reproduce in my case too. What am I doing wrong?

**Comment by witfyl-ravped** [comment]
I also get HH604 but with the following error text:

```
Error HH604: Error running JSON-RPC server: ERROR processing .../sushiswap-contracts/deploy/UniswapV2Router02.js:
Error: No deployment found for: WETH9Mock
```

Any insights here?

**Comment by dudhatparesh** [comment]
I am also getting 

Error HH604: Error running JSON-RPC server: ERROR processing .../sushiswap-contracts/deploy/UniswapV2Router02.js:
Error: No deployment found for: WETH9Mock

**Comment by yeahIamblonde** [comment]
I have the same problem. Why is this issue closed without giving a solution @matthewlilley?
