### ISSUE TITLE
Error: No deployment found for: WETH9Mock

### ISSUE THREAD

**Issue by youngqqcn** [sushiswap/sushiswap#99]
```
$ npx hardhat node
? Help us improve Hardhat with anonymous crash reports & basic usage data? (Y/n) ‣ (node:879722) Warning: Accessing non-existent property 'VERSION' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
✖ Help us improve Hardhat with anonymous crash reports & basic usage data? (Y/n) · true
Nothing to compile
Creating Typechain artifacts in directory types for target ethers-v5
Successfully generated Typechain artifacts!
deploying "UniswapV2Factory" (tx: 0x59e1bdf230a75035b662eb7ed727fb5c4cb9da81610ccb503f5df71a20600a0f)...: deployed at 0x5FbDB2315678afecb367f032d93F642f64180aa3 with 2508106 gas
Error HH604: Error running JSON-RPC server: ERROR processing /data/work/sushiswap/deploy/UniswapV2Router02.js:
Error: No deployment found for: WETH9Mock
    at Object.get (/data/work/sushiswap/node_modules/hardhat-deploy/src/DeploymentsManager.ts:127:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at runNextTicks (internal/process/task_queues.js:62:3)
    at listOnTimeout (internal/timers.js:523:9)
    at processTimers (internal/timers.js:497:7)
    at Object.module.exports [as func] (/data/work/sushiswap/deploy/UniswapV2Router02.js:13:20)
    at DeploymentsManager.executeDeployScripts (/data/work/sushiswap/node_modules/hardhat-deploy/src/DeploymentsManager.ts:989:22)
    at DeploymentsManager.runDeploy (/data/work/sushiswap/node_modules/hardhat-deploy/src/DeploymentsManager.ts:820:5)
    at Environment._runTaskDefinition (/data/work/sushiswap/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/data/work/sushiswap/node_modules/hardhat/src/internal/core/runtime-environment.ts:130:14)

For more info go to https://hardhat.org/HH604 or run Hardhat with --show-stack-traces
```

**Comment by youngqqcn** [comment]
I deployed WETH9 by myself before I deploy other contracts.

**Comment by huangyemin** [comment]
how do you solved this problem

**Comment by 8bitsout** [comment]
Hi @huangyemin I know this is a late response, but if you're blocked by this issue and want to resolve it, you can make the changes in this [PR](https://github.com/sushiswap/sushiswap/pull/85) specifically to ```UniswapV2Router02.js```.  This worked for me, hope it helps you out!
